name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install dpkg tools
      run: sudo apt-get install dpkg-dev debhelper javahelper
    - name: Build with Ant
      run: ver=$(git describe --match "Jitsi-[0-9\.]*" --long) && echo ${ver}
#    - name: Build with Ant
#      run: ant -noinput -buildfile build.xml -Dsplashscreen.enable=true -Dlabel=$((setvarStep.myOutputVar + 5236)) rebuild deb
