name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install dpkg tools
      run: sudo apt-get install dpkg-dev debhelper javahelper
    - script: echo "##vso[task.setvariable variable=countcommits;isOutput=true]$(git rev-list Jitsi-2.10..HEAD --count)"
      name: setvarStep
    - script: echo "##vso[task.setvariable variable=ver;isOutput=true]$(git describe --match "Jitsi-[0-9\.]*" --long)"
      name: setvarStep
#    - name: Build with Ant
#      run: ant -noinput -buildfile build.xml -Dsplashscreen.enable=true -Dlabel=$((setvarStep.myOutputVar + 5236)) rebuild deb
    - name: Build with Ant
      run: echo $((setvarStep.myOutputVar + 5236))
